# Generated by Django 6.0 on 2026-02-04 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userfollows",
            options={"verbose_name_plural": "User follows"},
        ),
    ]
